### PR TITLE
Update_05_09_15

### PR DESCRIPTION
**Pull request by Maranto**

### CODE REVIEW

**Comment by JamesB7** [comment]
Hello.

Is case really BOX and mod really MOD in Italian? Preheat as Booster also -- preheat is a specific term in English, is there no equivalent?

Thanks!

James

**Comment by Maranto** [comment]
Hello James,
the “case” in Italian is translated as a scatola, contenitore, astuccio, involucro.
Even for the  computer did not have a translation remained "case". In the world of Italian Vapers the case is the BOX or the tube!

While the MOD has never had a translation remained unchanged in Italian ...

"preheat" in Italian is literally translated as "Preheat".
No vaper uses this term and often kimono "Booster". Very few times I heard it called "Pre-activation"

Any time you decide to use it to welcome me!

Best regards!

Antonio

**Comment by Maranto** [comment]
Oooppps Preheat is litteral "Preattivazione" sorry :D

**Comment by JamesB7** [comment]
Is Booster the term even used for DNA 40's behavior? Preheat is 
specific, because it's not about giving a stronger vape, but getting to 
a vaping temperature quickly from cold. But, I don't know if that ever 
got translated to people. :)
BOX surprised me because it is an English word. If that is what people 
call it, that is fine. I was just surprised. Italians use all capital 
letters, too?

Thanks :)

James

**Comment by Maranto** [comment]
Hello James,
Booster is defined by DNA40, Dicodes DANI V2, dicodes little greek and other.
"Preriscaldamento" is the exact definition of the preheat in Italian but is little used. Does not sound good as a booster! LOL
Is in all ecommerce Italian called BOX: D

Italians like to use English and some terms are part of the vocabulary such as Booster http://www.treccani.it/enciclopedia/booster/

If you prefer you can change booster with "Preriscaldamento"

Thank you
Antonio

**Comment by Maranto** [comment]
Ciao,
You have no more interest in these translations?
Thanks for the reply, if any.

**Comment by JamesB7** [comment]
Hello Maranto, 

Sorry for the delay. Thank you for this translation! I will include it in the next version of EScribe.

Have a good day,

James

**Comment by JamesB7** [comment]
I do wonder about Booster though -- it doesn't tell people what exactly it does. Do the other chips using this term do it in the same way as DNA 200? Thanks! James

**Comment by Maranto** [comment]
Not really! Do not preheat. Only booster as DNA40.
But in my last translation I changed it to "PRERISCALDAMENTO = PreHeat" which is what makes DNA200.
Thanks for everything and greetings

**Comment by Maranto** [comment]
Hello.
Send me, please, Escribe parts of the new firmware to be translated into Italian?

Thanks!

**Pull request merged**
